name: Publish workflow

on:  
  push:
    tags:
      - '*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check out source code
              uses: actions/checkout@v2

            - name: Restore cache
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Set NPM registry
              uses: actions/setup-node@v1
              with:
                  node-version: '12'
                  registry-url: https://registry.npmjs.org

            - name: Installing NPM dependencies
              run: npm install

            - name: Publish NPM package
              if: startsWith(github.ref, 'refs/tags/v')
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
